baseURL = "http://localhost:1313/"
languageCode = 'cs-cz'
title = 'Zvaž vědu!'
uglyURLs = false
enableEmoji = true
[params]
    description = 'Oficiální stránky Zvaž vědu!'
[markup.goldmark.renderer]
    unsafe = true
[caches]
  [caches.images]
    dir = ':cacheDir/images'