name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch to deploy from (usually main)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if you use submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo entries

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # Specify Hugo version if needed

      - name: Build
        run: hugo --minify # Build your Hugo site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # The directory Hugo builds into
          publish_branch: gh-pages # The branch to publish to